"""Render a catalog app as a Docker Compose file, to be created in OpenMediaVault's Compose plugin.

The YAML is written by hand (JSON strings are valid YAML scalars) so this stays dependency free.
"""

import json
import re
from typing import Any, Dict, List, Optional

_NAME_RE = re.compile(r"[^a-z0-9_.-]+")


def compose_filename(app_id: str) -> str:
    """Name for the OMV Compose file (OMV uses it as the project name)."""
    return _NAME_RE.sub("-", app_id.strip().lower()).strip("-") or "app"


def build_compose_yaml(
    app: Dict[str, Any],
    ports: Optional[Dict[str, str]] = None,
    volumes: Optional[List[str]] = None,
) -> str:
    """ports maps host port -> container port, volumes are 'host:container' binds."""
    name = compose_filename(app["id"])
    ports = ports if ports is not None else app.get("ports", {})
    volumes = volumes if volumes is not None else app.get("volumes", [])
    env = app.get("env", [])

    q = json.dumps
    lines = [
        f"# {app.get('name', name)}: generated by ClaraOS. Paste into OMV > Services > Compose > Files > Create.",
        "services:",
        f"  {name}:",
        f"    image: {q(app['image'])}",
        f"    container_name: {q(name)}",
        "    restart: unless-stopped",
    ]
    if ports:
        lines.append("    ports:")
        lines += [f"      - {q(f'{host}:{container}')}" for host, container in ports.items()]
    if volumes:
        lines.append("    volumes:")
        lines += [f"      - {q(v)}" for v in volumes]
    if env:
        lines.append("    environment:")
        lines += [f"      - {q(e)}" for e in env]
    return "\n".join(lines) + "\n"
