#!/usr/bin/env python3
"""Auto-generate nginx host->port map for wildcard-gateway from running docker containers.

Output: <name>.* <hostport>;  (nginx map, `hostnames` mode). Manual entries in nginx.conf win;
this file only feeds the `default` fallback. Opt out with label gateway.enable=false,
override with labels gateway.subdomain=<name> and gateway.port=<hostport>.
"""
import json, os, subprocess, sys, time, tempfile

OUT = os.environ.get("AUTOMAP_OUT", "/docker-files/gateway/auto/apps-auto.conf")
GATEWAY = "wildcard-gateway"
# host ports that are never HTTP UIs
NON_HTTP = {21, 22, 25, 53, 110, 143, 445, 1883, 2049, 3306, 5432, 5433, 6379, 8883, 9092, 11211, 27017}
SKIP_NAMES = {GATEWAY, "claraos", "cloudflared"}


def sh(*a):
    return subprocess.run(a, capture_output=True, text=True, check=True).stdout


def build():
    ids = sh("docker", "ps", "-q").split()
    entries = {}
    if not ids:
        return entries
    for c in json.loads(sh("docker", "inspect", *ids)):
        name = c["Name"].lstrip("/")
        labels = c["Config"].get("Labels") or {}
        if name in SKIP_NAMES or name.startswith("cloudflared") or labels.get("gateway.enable") == "false":
            continue
        ports = []
        for cport, binds in ((c["NetworkSettings"].get("Ports")) or {}).items():
            if not binds or not cport.endswith("/tcp"):
                continue
            for b in binds:
                hp = int(b["HostPort"])
                if hp not in NON_HTTP and hp not in ports:
                    ports.append(hp)
        if labels.get("gateway.port"):
            ports = [int(labels["gateway.port"])]
        if not ports:
            continue
        names = {name, labels.get("com.docker.compose.service", ""), labels.get("gateway.subdomain", "")}
        for n in names:
            n = n.strip().lower()
            if n and all(ch.isalnum() or ch in "-_" for ch in n) and "_" not in n:
                entries.setdefault(n, min(ports))
    return entries


def render(entries):
    lines = ["# AUTO-GENERATED by gateway-automap. Do not edit."]
    lines += [f"{n}.*  {p};" for n, p in sorted(entries.items())]
    return "\n".join(lines) + "\n"


def apply(text):
    old = open(OUT).read() if os.path.exists(OUT) else ""
    if old == text:
        return False
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:   # in place; dir is bind-mounted
        f.write(text)
    t = subprocess.run(["docker", "exec", GATEWAY, "nginx", "-t"], capture_output=True, text=True)
    if t.returncode != 0:
        with open(OUT, "w") as f:
            f.write(old)
        print("nginx -t failed, reverted:", t.stderr[-300:], flush=True)
        return False
    subprocess.run(["docker", "exec", GATEWAY, "nginx", "-s", "reload"], check=True)
    print("map updated:", len(text.splitlines()) - 1, "entries", flush=True)
    return True


def main():
    if "--print" in sys.argv:
        print(render(build()), end="")
        return
    apply(render(build()))
    while True:
        p = subprocess.Popen(["docker", "events", "--filter", "type=container",
                              "--filter", "event=start", "--filter", "event=die", "--filter", "event=destroy", "--filter", "event=rename",
                              "--format", "{{.Action}}"], stdout=subprocess.PIPE, text=True)
        for _ in p.stdout:
            time.sleep(3)  # debounce bursts
            try:
                apply(render(build()))
            except Exception as e:
                print("error:", e, flush=True)
        time.sleep(5)


if __name__ == "__main__":
    main()
